### ISSUE TITLE
Repeated error: Could not determine client ID from request

### ISSUE THREAD

**Issue by palp** [getsentry/sentry-auth-google#36]
I have a fresh docker-based installation of Sentry 9.1.1 configured with Google auth. Since setting it up, I have seen the following error repeated in the internal project twice an hour:

> AuthIdentity(id=1) returned an error during validation: HTTP 400 (invalid_request): Could not determine client ID from request

This does not seem to be impacting anything, as I am able to log in using Google with no issues. Note that no one was logged in during most of these, and they seem to be occurring on a schedule, so I assume some automated process is triggering the errors. 

![image](https://user-images.githubusercontent.com/232217/57989488-2946f800-7a50-11e9-9117-de9cb15ad4a9.png)

**Comment by gordcorp** [comment]
I am seeing the same thing in 9.1.1, and it used to happen on 9.0 as well.

**Comment by dionrhys** [comment]
I'm also experiencing this issue. This is a fresh setup of Sentry 9.1.2 in Docker. It seems to be happening 4 times per hour usually.

![Screenshot of this issue in Sentry](https://user-images.githubusercontent.com/844245/63754354-a3d3af00-c8ac-11e9-97ca-43d68cd463dc.png)

We're setting the client ID and secret in sentry.conf.py like so:

```
SENTRY_OPTIONS['auth-google.client-id'] = "..."
SENTRY_OPTIONS['auth-google.client-secret'] = "..."
```

**Comment by dionrhys** [comment]
I've figured out why we're having this issue.

Sentry 9.1+ now has the Google Auth provider built-in, and there's no need for this separate package to be installed. (See https://github.com/getsentry/sentry/tree/9.1.0/src/sentry/auth/providers/google)

This standalone package doesn't understand the new options-based format with `auth-google.client-id` and `auth-google.client-secret` so its client ID and secret was always unset, and it was also running at the same time as Sentry's built-in Google auth provider.

We fixed this problem by just removing the `sentry-auth-google` package from requirements.txt so that only Sentry's built-in provider would be used.

**Comment by jamiecounsell** [comment]
Same as @hypnoglow here. No `sentry-auth-google` package but still seeing this error in a fresh Docker install with Google auth enabled.

**Comment by renatgalimov** [comment]
I confirm. Fresh 9.1.2 with Google auth is not working.

**Comment by dcramer** [comment]
Just for some clarity here - we dont support the 9.x series anymore. Feel free to re-open this ticket if the problem is still present in the 10.x (latest) series.
